const SITE = {
  name: 'Sahil Jain',
  email: 'sahiljain0006@gmail.com',
  phone: '+91 7200123990',
  location: 'Tambaram, Chennai, India',
  github: 'https://github.com/sahiljain006',
  linkedin: 'https://linkedin.com/in/sahiljain0006',
  instagram: 'https://instagram.com/sahil.jain006',
  roles: ['Software Developer','Full Stack Developer','AI Enthusiast','Python Developer'],
  stats: [
    { number: 5, suffix: '+', label: 'Projects Built' },
    { number: 10, suffix: '+', label: 'Certifications' },
    { number: 25, suffix: '+', label: 'Technologies' },
    { number: 3, suffix: '+', label: 'Hackathons' },
  ],
  skills: [
    { title: 'Programming Languages', icon: '<svg viewBox="0 0 24 24" width="22" height="22" fill="#3776AB"><path d="M11.914 0C5.82 0 6.2 2.656 6.2 2.656l.007 2.752h5.814v.828H3.9S0 5.789 0 11.969c0 6.18 3.394 5.98 3.394 5.98h2.01v-2.866s-.108-3.394 3.34-3.394h5.766s3.234.052 3.234-3.128V3.254S18.13 0 11.914 0zM8.708 1.84a1.052 1.052 0 011.052 1.052 1.052 1.052 0 01-1.052 1.052A1.052 1.052 0 017.656 2.892 1.052 1.052 0 018.708 1.84z"/><path d="M12.086 24c6.094 0 5.714-2.656 5.714-2.656l-.007-2.752h-5.814v-.828h8.121S24 18.211 24 12.031c0-6.18-3.394-5.98-3.394-5.98h-2.01v2.866s.108 3.394-3.34 3.394h-5.766s-3.234-.052-3.234 3.128v5.334S5.87 24 12.086 24zm3.206-1.84a1.052 1.052 0 01-1.052-1.052 1.052 1.052 0 011.052-1.052 1.052 1.052 0 011.052 1.052 1.052 1.052 0 01-1.052 1.052z"/><path d="M11.914 0C5.82 0 6.2 2.656 6.2 2.656l.007 2.752h5.814v.828" fill="#FFD43B"/></svg>', color: 'rgba(184,173,255,0.12)', items: [
      { name: 'Python', desc: 'Core language for backend, AI, and scripting' },
      { name: 'Java', desc: 'OOP, data structures, and algorithm design' },
      { name: 'C++', desc: 'Competitive programming and system-level logic' },
    ]},
    { title: 'Frontend', icon: '<svg viewBox="0 0 24 24" width="22" height="22" fill="none"><path d="M4 2l1.5 18L12 22l6.5-2L20 2H4z" fill="#E44D26"/><path d="M12 2v20l5.5-1.5L19.5 4 12 2z" fill="#F16529"/><path d="M12 7.5l-.3 3.2 5.5.1-.5 5.7L12 18l-4.7-1.5.3-3.5H5l-.8 8.5L12 22" fill="#EBEBEB"/></svg>', color: 'rgba(255,181,167,0.12)', items: [
      { name: 'HTML', desc: 'Semantic markup and accessible interfaces' },
      { name: 'CSS', desc: 'Responsive layouts, animations, modern design' },
      { name: 'JavaScript', desc: 'Interactive UI, DOM manipulation, APIs' },
    ]},
    { title: 'Backend', icon: '<svg viewBox="0 0 24 24" width="22" height="22" fill="#0C4B33"><path d="M7.794 0c-.432 0-.83.216-1.08.576L.144 17.136h4.752l1.08-3.024h7.488l1.08 3.024h5.256L13.554.576C13.302.216 12.906 0 12.474 0H7.794zm-.144 4.608l2.448 6.912H5.202l2.448-6.912z"/></svg>', color: 'rgba(103,232,249,0.12)', items: [
      { name: 'Python', desc: 'Business logic, data processing, scripting' },
      { name: 'Django', desc: 'Full-stack web application framework' },
      { name: 'DRF', desc: 'REST API development and serialization' },
    ]},
    { title: 'Database', icon: '<svg viewBox="0 0 24 24" width="22" height="22" fill="none"><ellipse cx="12" cy="5" rx="9" ry="3" stroke="#00758F" stroke-width="2"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3" stroke="#00758F" stroke-width="2"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5" stroke="#00758F" stroke-width="2"/><ellipse cx="12" cy="12" rx="9" ry="3" fill="#F29111" opacity="0.15"/></svg>', color: 'rgba(253,186,116,0.12)', items: [
      { name: 'SQLite', desc: 'Lightweight embedded database for apps' },
      { name: 'MySQL', desc: 'Relational database for production systems' },
    ]},
    { title: 'Developer Tools', icon: '<svg viewBox="0 0 24 24" width="22" height="22" fill="#F05032"><path d="M23.546 10.93L13.067.452a1.55 1.55 0 00-2.186 0L8.708 2.627l2.76 2.76a1.838 1.838 0 012.327 2.341l2.645 2.645a1.838 1.838 0 11-1.18 1.088l-2.47-2.47v6.51a1.838 1.838 0 11-1.532-.065V9.36a1.838 1.838 0 01-1.002-2.41L7.6 4.227-.164 11.99a1.55 1.55 0 000 2.186l10.48 10.48a1.55 1.55 0 002.186 0l10.04-10.04a1.55 1.55 0 000-2.186z"/></svg>', color: 'rgba(253,164,175,0.12)', items: [
      { name: 'Git', desc: 'Version control and collaboration' },
      { name: 'GitHub', desc: 'Code hosting, PRs, and project management' },
      { name: 'VS Code', desc: 'Primary development environment' },
      { name: 'Postman', desc: 'API testing and documentation' },
    ]},
    { title: 'AI Tools', icon: '<svg viewBox="0 0 24 24" width="22" height="22" fill="none"><circle cx="12" cy="12" r="3" fill="#7C3AED"/><path d="M12 2a4 4 0 014 4v2a4 4 0 01-8 0V6a4 4 0 014-4z" stroke="#7C3AED" stroke-width="2"/><path d="M6 10h12l1 10H5L6 10z" stroke="#A78BFA" stroke-width="2"/><circle cx="10" cy="16" r="1" fill="#7C3AED"/><circle cx="14" cy="16" r="1" fill="#7C3AED"/></svg>', color: 'rgba(167,139,250,0.12)', items: [
      { name: 'ChatGPT', desc: 'AI-assisted development and research' },
      { name: 'Claude', desc: 'Advanced reasoning and code analysis' },
      { name: 'Prompt Engineering', desc: 'Crafting effective AI interactions' },
    ]},
  ],
  projects: [
    {
      id: 'futurelens', title: 'FutureLens', sub: 'AI-Powered Career Intelligence',
      desc: 'An intelligent career guidance platform that leverages multiple assessment frameworks to deliver personalized career pathways, learning roadmaps, and actionable insights for students navigating their professional journey.',
      problem: 'Students often struggle to find the right career path due to lack of personalized guidance and overwhelming options.',
      solution: 'Built an AI-driven assessment engine that analyzes user responses across multiple frameworks and generates tailored career recommendations with interactive visualizations.',
      features: ['Multi-framework assessments','AI-powered career matching','Personalized learning roadmaps','Interactive dashboard','Responsive design'],
      stack: ['Python','Django','DRF','SQLite','AI/ML','JavaScript'],
      badge: 'ai', mockGrad: 'linear-gradient(135deg,#F0EDFF,#EDE9FE)', image: 'assets/FUTURELENS HERO.png',
      github: 'https://github.com/sahiljain006/FutureLens',
    },
    {
      id: 'tap', title: "TAP — That's A Plan", sub: 'Event Management Platform',
      desc: 'A full-stack event management platform with secure REST APIs, JWT authentication, role-based access control, and a clean responsive interface for seamless event lifecycle management.',
      problem: 'Event organizers need a centralized, secure platform to create, manage, and track events with proper access control.',
      solution: 'Designed a Django REST Framework backend with JWT auth and a responsive frontend for seamless event lifecycle management.',
      features: ['Secure REST APIs','JWT Authentication','Role-based access control','Event CRUD operations','Responsive UI'],
      stack: ['Python','Django','DRF','SQLite','JavaScript','Bootstrap'],
      badge: 'fs', mockGrad: 'linear-gradient(135deg,#FFF0ED,#F5F3FF)', image: 'assets/TAP HERO.png',
      github: 'https://github.com/sahiljain006/TAP-That-s-A-Plan',
    },
    {
      id: 'foodshare', title: 'FoodShare', sub: 'Smart Food Donation Platform',
      desc: 'A community-driven platform that connects food donors with NGOs and volunteers to reduce food waste. Features real-time donation listings, pickup management, expiry tracking, live dashboard analytics, and Google Maps integration for seamless food distribution.',
      problem: 'Millions of tons of food are wasted daily while communities nearby go hungry, with no efficient system to connect donors with those in need.',
      solution: 'Built a real-time donation platform with Maps integration, expiry tracking, and a live dashboard to streamline the food distribution workflow from donor to recipient.',
      features: ['Real-time donation listings','Pickup management','Expiry tracking','Live dashboard analytics','Google Maps integration'],
      stack: ['HTML','CSS','JavaScript','Local Storage','Google Maps API'],
      badge: 'web', mockGrad: 'linear-gradient(135deg,#ECFDF5,#ECFEFB)', image: 'assets/FOODSHARE HERO.png',
      github: 'https://github.com/sahiljain006/FoodShare',
    },
    {
      id: 'sandeepjewels', title: 'Sri Sandeep Jewels', sub: 'Premium Jewellery Showcase',
      desc: 'A modern and responsive e-commerce showcase website designed for an imitation jewellery brand. Features elegant product collections, category-based filtering, interactive product cards, WhatsApp ordering, responsive layouts, and premium UI animations to deliver a seamless shopping experience for customers.',
      problem: 'A jewellery brand needs a premium online presence that showcases their collections elegantly and makes it easy for customers to browse and order.',
      solution: 'Built a responsive showcase website with category filtering, interactive product cards, and WhatsApp integration for seamless customer engagement and ordering.',
      features: ['Elegant product collections','Category-based filtering','Interactive product cards','WhatsApp ordering','Premium UI animations'],
      stack: ['HTML','CSS','JavaScript','Responsive Design','WhatsApp API'],
      badge: 'web', mockGrad: 'linear-gradient(135deg,#FFF7ED,#FFFBEB)', image: 'assets/SANDEEP JEWELS HERO.png',
      github: 'https://github.com/sahiljain006',
    },
    {
      id: 'portfolio', title: 'Personal Portfolio', sub: 'Developer Showcase',
      desc: 'A premium personal portfolio crafted to reflect my design philosophy, technical expertise, and development journey. Built with modern UI, smooth animations, responsive layouts, and refined interactions to deliver a memorable user experience.',
      problem: 'A developer needs a polished online presence that reflects their skills and attention to detail.',
      solution: 'Created this portfolio with custom animations, smooth scrolling, and a clean editorial design that tells a story.',
      features: ['Responsive layout','Custom animations','Smooth scrolling','SEO optimized','Performance focused'],
      stack: ['HTML','CSS','JavaScript','GSAP','Tailwind CSS'],
      badge: 'web', mockGrad: 'linear-gradient(135deg,#F3EFFE,#F0EDFF)', image: 'assets/PORTFOLIO HERO.png',
      github: 'https://github.com/sahiljain006/TNSDC-FWD-DigitalPortfolio',
    },
  ],
  certifications: [
    { title: 'Fullstack Web Development', org: 'Udemy', short: 'UD', type: 'Professional', desc: 'Comprehensive full stack web development training covering frontend, backend, databases, and deployment workflows.', image: 'assets/UDEMY FULLSTACK WEB DEV CERTIFICATE.jpg' },
    { title: 'Web Development Fundamentals', org: 'IBM', short: 'IBM', type: 'Certified', desc: 'Foundational web development skills covering HTML, CSS, JavaScript, and modern web architecture principles.', image: 'assets/IBM WEB DEV FUNDAMENTALS CERTIFICATE.jpg' },
    { title: 'Python for Data Science', org: 'NPTEL', short: 'NP', type: 'Elite', desc: 'Comprehensive Python programming for data science applications including manipulation, analysis, and visualization techniques.', image: 'assets/PYTHON DATA SCIENCE CERTIFICATE.jpg' },
    { title: 'Cloud Computing & Distributed Systems', org: 'NPTEL', short: 'NP', type: 'Certified', desc: 'Cloud computing architectures, distributed systems principles, and modern deployment strategies.', image: 'assets/NPTEL CLOUD COMPUTING CERTIFICATE.jpg' },
    { title: 'AI Tools & ChatGPT Workshop', org: 'Be10x', short: 'B10', type: 'Workshop', desc: 'Hands-on exploration of AI tools, ChatGPT capabilities, and prompt engineering for developer productivity.', image: 'assets/BE10X AI CERTIFICATE.jpg' },
    { title: 'Generative AI for All', org: 'Infosys Springboard', short: 'IS', type: 'Certified', desc: 'Introduction to generative AI concepts, large language models, and practical applications across industries.', image: 'assets/INFOSYS GEN AI CERTIFICATE.jpg' },
    { title: 'AI Powered Full Stack Workshop', org: 'NTech', short: 'NW', type: 'Workshop', desc: 'Intensive workshop on integrating AI capabilities into full stack applications using modern frameworks.', image: 'assets/AI FULLSTACK CERTIFICATE.jpg' },
    { title: 'Python Full Stack Internship', org: 'Nexila Technologies', short: 'NT', type: 'Professional', desc: 'Full stack development covering backend APIs, frontend integration, database management, and deployment.', image: 'assets/NEXILA FULL STACK CERTIFICATE.jpg' },
  ],
  achievements: [
    { icon: '🏆', title: 'Smart India Hackathon', desc: 'Participated in India\'s largest hackathon, building innovative solutions for real-world problems under intense 36-hour time constraints.' },
    { icon: '🎓', title: 'Technical Workshops', desc: 'Conducted and attended multiple workshops on AI tools, full stack development, and modern web technologies.' },
    { icon: '💻', title: 'Hackathon Projects', desc: 'Built and presented projects at multiple hackathons, demonstrating rapid prototyping and team collaboration skills.' },
    { icon: '📋', title: 'Internship at Nexila', desc: 'Successfully completed Python Full Stack Internship, contributing to production-ready backend systems and APIs.' },
    { icon: '📚', title: 'Continuous Learning', desc: 'Committed to lifelong learning through certifications, online courses, and hands-on project development.' },
    { icon: '🚀', title: 'Open Source Growth', desc: 'Actively studying open source codebases and learning from industry-standard frameworks and tools.' },
  ],
  github: {
    username: 'sahiljain006',
    repos: 8, contributions: 350, followers: 25, stars: 12,
    languages: [
      { name: 'Python', color: '#B8ADFF', pct: 55 },
      { name: 'JavaScript', color: '#FFB8A7', pct: 20 },
      { name: 'HTML', color: '#FDA4AF', pct: 12 },
      { name: 'CSS', color: '#C4B5FD', pct: 8 },
      { name: 'Other', color: '#9CA3AF', pct: 5 },
    ],
  },
  timeline: [
    { year: 'Beginnings', title: 'Started programming', desc: 'First lines of code, driven by curiosity about how software actually works.' },
    { year: 'Early builds', title: 'Built first website', desc: 'Moved from syntax to shipping — real pages, real deployments.' },
    { year: 'Foundations', title: 'Python development', desc: 'Deepened core programming skills with Python across scripting, logic and data.' },
    { year: 'Growth', title: 'Full-stack development', desc: 'Learned to connect frontend, backend and databases into complete products with Django, React and MySQL.' },
    { year: 'Competing', title: 'Hackathons & events', desc: 'Tested ideas under pressure, collaborating in fast-paced build sprints.' },
    { year: 'Applying', title: 'Internship experience', desc: 'Brought academic skill into a professional, production-facing environment.' },
    { year: 'Exploring', title: 'AI-powered projects', desc: 'Started building tools that use AI APIs and prompting to solve real problems.' },
    { year: 'Ongoing', title: 'Continuous learning', desc: 'Still a student by title — always a builder by habit.' },
  ],
};
